#!/usr/bin/env python

import sys

assert len(sys.argv) > 1, "Pass a file name"

import molparse as mp

sys = mp.parse(sys.argv[1], alternative_site_warnings=False)

if isinstance(sys, list):
    if len(sys) == 1:
        sys = sys[0]

sys.tree()
