#!/usr/bin/env python3

import sys

assert len(sys.argv) > 1, "Pass a file name"

import molparse as mp

sys = mp.parse(sys.argv[1])

if isinstance(sys, list):
	if len(sys) == 1:
		sys = sys[0]

sys.tree()
